apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-diploma
  namespace: diploma
  labels:
    app: nginx-diploma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-diploma
  template:
    metadata:
      labels:
        app: nginx-diploma
    spec:
      containers:
        - name: nginx
          image: aykapranov/nginx-diploma:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-diploma
  namespace: diploma
spec:
  type: ClusterIP
  selector:
    app: nginx-diploma
  ports:
    - name: http
      port: 80
      targetPort: 80
